version: 2
updates:
  - package-ecosystem: npm
    directory: /website
    schedule:
      interval: weekly
    groups:
      nextjs:
        patterns:
          - next
          - eslint-config-next
      dependencies:
        patterns:
          - '*'
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      dependencies:
        patterns:
          - '*'
